language: node_js
node_js:
  - "8"
install:
  - npm install
  - npm install gulp vinyl-ftp minimist gulp-images-resizer fancy-log --save-dev
script:
  - gulp build
after_success:
  gulp deploy --user $FTP_USER --password $FTP_PASSWORD --server $FTP_SERVER
