language: node_js
node_js:
  - "8"
before_install: 
  - chmod +x web_deploy.sh
install:
  - npm install
  - npm install gulp gulp-images-resizer --save-dev
script:
  - gulp build
after_success:
  - ./web_deploy.sh
